micronaut:
  application:
    name: fileService
  server:
    max-request-size: 10485760
netty:
  default:
    allocator:
      max-order: 3
app:
  root-dir: .
  max-file-chunk-size: 10485760
  file-locking:
    enabled: true
    read-timeout: 1000ms
    write-timeout: 1000ms
  file-service:
    pool-size: 10
  simple-allocator:
    enabled: true
    buffer-size: 8192