micronaut:
  application:
    name: fileService
netty:
  default:
    allocator:
      max-order: 3
app:
  root-dir: .
  buffer-pool:
    enabled: false
    size: 1024
    buffer-size: 8192
  max-file-chunk-size: 10485760
  simple-allocator:
    enabled: true
    buffer-size: 8192