image:
  name: file-service
  tag: latest
  pullPolicy: IfNotPresent
app:
  jvmOptions: "-Xmx1024m"
  port: 8080
  host: 0.0.0.0
  config:
    rootDir: .
resources:
  requests:
    cpu: 1000m
    memory: 1024Mi