apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fs-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    k8s-app: file-service
spec:
  selector:
    matchLabels:
      k8s-app: file-service
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: file-service
    spec:
      containers:
        - name: file-service-container
          image: {{ .Values.image.name }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: JVM_OPTIONS
              value: "{{ .Values.app.jvmOptions }}"
            - name: MICRONAUT_SERVER_HOST
              value: "{{ .Values.app.host }}"
            - name: MICRONAUT_SERVER_PORT
              value: "{{ .Values.app.port }}"
            - name: APP_ROOT_DIR
              value: "{{ .Values.app.config.rootDir }}"
            - name: APP_MAX_FILE_CHUNK_SIZE
              value: "{{ .Values.app.config.maxFileChunkSize }}"
            - name: MICRONAUT_SERVER_MAX_REQUEST_SIZE
              value: "{{ .Values.app.config.maxRequestSize }}"
