apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    k8s-app: file-service
spec:
  selector:
    matchLabels:
      k8s-app: file-service
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: file-service
    spec:
      containers:
        - name: file-service-container
          image: {{ .Values.image.name }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
